# ==================================================================
# 🚀 INDUSTRY-LEADING SECRET SCANNING CONFIGURATION
# ✅ Prevents Leaks, Secures API Keys, Automates Secret Rotation
# ==================================================================

# ------------------------------------------------------------
# 🔹 **Secret Scanning Rules and Patterns**
# ------------------------------------------------------------
secrets:
  enable_secret_scanning: true  # Enable or disable secret scanning
  allowlisted_secrets:  # Define allowed (safe) secrets (used for testing or non-sensitive cases)
    - "SAFE_TEST_KEY_1234"
  patterns:
    - "(?i)apikey[=:\"'\s]*([a-z0-9-_]{32,64})"
    - "(?i)secret[=:\"'\s]*([a-z0-9-_]{32,64})"
    - "(?i)password[=:\"'\s]*([a-z0-9-_!@#$%^&*]{8,})"
    - "(?i)token[=:\"'\s]*([a-z0-9-_]{32,64})"
    - "(?i)aws_access_key_id[=:\"'\s]*([A-Z0-9]{20})"
    - "(?i)aws_secret_access_key[=:\"'\s]*([A-Za-z0-9/+=]{40})"
    - "(?i)gcp_service_account[=:\"'\s]*([a-z0-9-]+@[a-z0-9-.]+\\.iam\\.gserviceaccount\\.com)"
    - "(?i)azure_client_secret[=:\"'\s]*([A-Za-z0-9-_]{32,64})"
    - "(?i)github_pat[=:\"'\s]*([a-z0-9_-]{40})"

# ------------------------------------------------------------
# 🔹 **Repositories & Files to Scan**
# ------------------------------------------------------------
repositories:
  - "github.com/RJV-TECHNOLOGIES-LTD/Model"  # GitHub repository for Unified Model AI
  - "gitlab.com/RJV-Tech/AI-Execution"
  - "bitbucket.org/RJV-Security/Secrets"

files:
  include:
    - "**/*.py"
    - "**/*.yml"
    - "**/*.json"
    - "**/*.env"
    - "**/*.sh"
  exclude:
    - "**/test/**"
    - "**/mock_data/**"
    - "**/logs/**"

# ------------------------------------------------------------
# 🔹 **CI/CD Integration (Secret Scanning on Pull Requests)**
# ------------------------------------------------------------
ci_cd_integrations:
  enable_github_actions: true  # Enable GitHub Advanced Security Secret Scanning
  enable_gitlab_ci: true  # Enable GitLab Secret Scanning
  enable_azure_devops_pipelines: true  # Enable Secret Scanning in Azure DevOps
  enable_jenkins: true  # Enable Jenkins plugin for secrets scanning

# ------------------------------------------------------------
# 🔹 **Secret Rotation & Automatic Revocation**
# ------------------------------------------------------------
secret_rotation:
  enable_automatic_rotation: true
  rotation_frequency_days: 30  # Rotate secrets every 30 days
  revoke_on_leak: true  # Automatically revoke secrets if leaked
  auto_generate_new_keys: true  # Auto-generate and store new keys securely

# ------------------------------------------------------------
# 🔹 **Secure Storage & Encryption Policies**
# ------------------------------------------------------------
storage:
  encryption_enabled: true  # Encrypt stored secrets
  encryption_algorithm: "AES-256"  # Use AES-256 encryption
  secret_managers:
    - aws_secrets_manager
    - azure_key_vault
    - gcp_secret_manager
  access_control:
    enable_role_based_access: true
    allow_roles:
      - "admin"
      - "security_team"
      - "devops"

# ------------------------------------------------------------
# 🔹 **Alerting & Logging Policies**
# ------------------------------------------------------------
alerts:
  enable_slack_notifications: true  # Send alerts to Slack
  slack_channel: "#security-alerts"
  enable_email_notifications: true  # Send email alerts
  email_recipients:
    - "security@rjvtech.com"
    - "devops@rjvtech.com"
  enable_webhook_notifications: true  # Webhook alerts for custom integrations
  webhook_url: "https://webhooks.rjvtech.com/security-alerts"

logging:
  enable_audit_logging: true
  log_file: "/var/log/secret_scanning.log"
  log_level: "INFO"
  retention_days: 90  # Store logs for 90 days

# ------------------------------------------------------------
# 🔹 **Intrusion Detection & Security Enforcement**
# ------------------------------------------------------------
intrusion_detection:
  enable_anomaly_detection: true
  detect_unusual_access_patterns: true
  monitor_repeated_failed_logins: true
  auto_block_suspicious_activity: true
  block_threshold: 5  # Block after 5 failed attempts
  firewall_rules:
    - allow: "10.0.0.0/8"  # Allow internal network
    - deny: "0.0.0.0/0"  # Block all public access unless explicitly allowed

# ------------------------------------------------------------
# 🔹 **Compliance & Governance Policies**
# ------------------------------------------------------------
compliance:
  enable_gdpr_compliance: true  # Ensure GDPR compliance for sensitive data
  enable_sarbanes_oxley: true  # Enforce Sarbanes-Oxley Act (SOX) compliance
  enable_iso_27001: true  # Ensure ISO 27001 security policies
  enable_nist_compliance: true  # Follow NIST security guidelines

# ------------------------------------------------------------
# 🔹 **Backup & Disaster Recovery**
# ------------------------------------------------------------
backup:
  enable_backup: true
  backup_frequency_days: 7  # Backup every 7 days
  backup_encryption: true  # Encrypt backup files
  backup_retention_days: 180  # Keep backups for 180 days
  backup_storage:
    - aws_s3
    - azure_blob_storage
    - gcp_cloud_storage

