apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference-deployment
  labels:
    app: ai-inference
spec:
  replicas: 2  # Run 2 instances for scalability
  selector:
    matchLabels:
      app: ai-inference
  template:
    metadata:
      labels:
        app: ai-inference
    spec:
      containers:
      - name: ai-inference-container
        image: ghcr.io/rjv-technologies-ltd/model/ai-inference:latest
        ports:
        - containerPort: 5000  # REST API
        - containerPort: 50051 # gRPC API
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        env:
        - name: MODEL_PATH
          value: "/app/memory_storage/model_checkpoints.h5"
        volumeMounts:
        - name: model-storage
          mountPath: /app/memory_storage
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ai-inference-service
spec:
  type: LoadBalancer
  selector:
    app: ai-inference
  ports:
    - name: rest-api
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: grpc-api
      protocol: TCP
      port: 50051
      targetPort: 50051

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Allocate 5GB for model storage
