ab_testing:
  enabled: true
  control_model: "model_v1.pkl"
  test_model: "model_v2.pkl"
  traffic_split: 50  # Percentage of requests sent to test model
  evaluation_metrics:
    - accuracy
    - recall
    - precision
    - latency
