apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference-service
  labels:
    app: ai-inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-inference
  template:
    metadata:
      labels:
        app: ai-inference
    spec:
      containers:
      - name: ai-inference-container
        image: ai-inference:latest  # Replace with your actual container image
        ports:
        - containerPort: 5000  # REST API
        - containerPort: 50051 # gRPC API
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-inference-service
spec:
  type: LoadBalancer
  selector:
    app: ai-inference
  ports:
    - name: rest-api
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: grpc-api
      protocol: TCP
      port: 50051
      targetPort: 50051
