name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/ai-inference:latest .
        docker tag ghcr.io/${{ github.repository }}/ai-inference:latest ghcr.io/${{ github.repository }}/ai-inference:${{ github.sha }}

    - name: Push Docker Image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/ai-inference:latest
        docker push ghcr.io/${{ github.repository }}/ai-inference:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment_automation/kubernetes_service.yaml
        kubectl rollout status deployment/ai-inference-service
